name: "Build, Test & Test Coverage"
# Runs on main branch commits, 
# every commit in a pull request, any published release.
on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  release:
    types: [published]
jobs:
  build:
    name: "Build & Test"
    # Permissions this GitHub Action needs for other things in GitHub
    permissions: write-all
    runs-on: windows-latest # Using Windows since your project is Windows-based
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      # Using the approach that worked in powershell
      - name: Test with code coverage
        run: dotnet test --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      
      # Add a diagnostic step to verify coverage files were created
      - name: Verify coverage files
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path ${{ github.workspace }} -Filter "coverage.cobertura.xml" -Recurse
          foreach ($file in $files) {
            Write-Output "Found coverage file: $($file.FullName)"
          }
          if ($files.Count -eq 0) {
            Write-Output "No coverage files found!"
          }
      
      - name: Combine Coverage Reports
        uses: danielpalme/ReportGenerator-GitHub-Action@v5.4.7
        with:
          reports: "**/coverage.cobertura.xml" # Updated path to match coverlet.msbuild output
          targetdir: "${{ github.workspace }}"
          reporttypes: "Cobertura"
          verbosity: "Info"
          title: "Code Coverage"
          tag: "${{ github.run_number }}_${{ github.run_id }}"
      
      - name: Upload Combined Coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ${{ github.workspace }}/Cobertura.xml
          retention-days: 5
      
      - name: Publish Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "Cobertura.xml"
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "10 30"
          
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      
      - name: Upload Test Result Files
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/**/TestResults/**/*
          retention-days: 5
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          trx_files: "${{ github.workspace }}/**/*.trx"
